<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#The-Python-Programming-Language:-Variables-and-Types" data-toc-modified-id="The-Python-Programming-Language:-Variables-and-Types-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>The Python Programming Language: Variables and Types</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Operations-with-strings" data-toc-modified-id="Operations-with-strings-1.0.1"><span class="toc-item-num">1.0.1&nbsp;&nbsp;</span>Operations with strings</a></span></li><li><span><a href="#Functions" data-toc-modified-id="Functions-1.0.2"><span class="toc-item-num">1.0.2&nbsp;&nbsp;</span>Functions</a></span></li><li><span><a href="#Conditional-statements" data-toc-modified-id="Conditional-statements-1.0.3"><span class="toc-item-num">1.0.3&nbsp;&nbsp;</span>Conditional statements</a></span></li></ul></li></ul></li><li><span><a href="#The-Python-Programming-Language:-Advanced-Types" data-toc-modified-id="The-Python-Programming-Language:-Advanced-Types-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>The Python Programming Language: Advanced Types</a></span><ul class="toc-item"><li><span><a href="#Lists" data-toc-modified-id="Lists-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Lists</a></span></li><li><span><a href="#Tuples" data-toc-modified-id="Tuples-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Tuples</a></span></li><li><span><a href="#Dictionaries" data-toc-modified-id="Dictionaries-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Dictionaries</a></span></li></ul></li><li><span><a href="#The-Python-Programming-Language:-Dates-and-Times" data-toc-modified-id="The-Python-Programming-Language:-Dates-and-Times-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>The Python Programming Language: Dates and Times</a></span></li><li><span><a href="#The-Python-Programming-Language:-Lambda-and-List-Comprehensions" data-toc-modified-id="The-Python-Programming-Language:-Lambda-and-List-Comprehensions-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>The Python Programming Language: Lambda and List Comprehensions</a></span></li><li><span><a href="#The-Python-Programming-Language:-Numerical-Python-(NumPy)" data-toc-modified-id="The-Python-Programming-Language:-Numerical-Python-(NumPy)-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>The Python Programming Language: Numerical Python (NumPy)</a></span><ul class="toc-item"><li><span><a href="#Creating-Arrays" data-toc-modified-id="Creating-Arrays-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Creating Arrays</a></span></li><li><span><a href="#Operations" data-toc-modified-id="Operations-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Operations</a></span></li><li><span><a href="#Math-Functions" data-toc-modified-id="Math-Functions-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Math Functions</a></span></li><li><span><a href="#Indexing-/-Slicing" data-toc-modified-id="Indexing-/-Slicing-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Indexing / Slicing</a></span></li><li><span><a href="#Copying-Data" data-toc-modified-id="Copying-Data-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>Copying Data</a></span><ul class="toc-item"><li><span><a href="#Iterating-Over-Arrays" data-toc-modified-id="Iterating-Over-Arrays-5.5.1"><span class="toc-item-num">5.5.1&nbsp;&nbsp;</span>Iterating Over Arrays</a></span></li></ul></li></ul></li></ul></div>

# The Python Programming Language: Variables and Types

In [4]:
x = 10
y = 20
print(x + y)
print(x*y)

30
200


In [5]:
y3=5

print(y3)

5


In [6]:
x

10

In [7]:
y2 = 43
y2

43

this is **text**

In [8]:
print (x,y,type(x), type(y))  #use print for multiple outputs

10 20 <class 'int'> <class 'int'>


In [9]:
x=1.
y=2.
z = x/y
print(type(x))
print (z)
print (type(z))

<class 'float'>
0.5
<class 'float'>


In [10]:
type(False)

bool

In [11]:
s='this is a string'
print (s)
print (type(s))

this is a string
<class 'str'>


<br>
Now let's look at strings. Use bracket notation to slice a string.

In [12]:
print(s[0]) #first character, python indexing starts from 0
print(s[0:2]) #first character, the last index (1) is not included
print(s[0:4]) #first two characters, the last index (2) is not included


t
th
this


In [13]:
print (s[-1])
# the last character
print (s[-4:-2])  # slice starting from the 4th element from the end and stopping before the 2nd element from the end
print (s[3:])    # slice starting from the 3rd element of the string and going all the way to the end

g
ri
s is a string


### Operations with strings

In [14]:
firstname = 'Jean'
lastname = "Dupont"   # You can either use quotes or double quotes for strings

print(firstname + ' ' + lastname)
print(firstname*3)
print('Chris' in firstname)
print('Jea' in firstname)

Jean Dupont
JeanJeanJean
False
True


In [16]:
fullname= 'Jean Dupont'
fullname.split(' ')  # Split the string on the space character

['Jean', 'Dupont']

In [17]:
'Jean'+ 2

TypeError: can only concatenate str (not "int") to str

In [19]:
'Jean '+ str(2) # Make sure you convert objects to strings before concatenating

'Jean 2'

<br>
Python has a built in method for convenient string formatting.

In [22]:
price = 3.24
num_items = 5
year = 2018
print('the price for the year',year,'is',price)
print("the price is %i" %num_items)
print("the price is %f" %price)
print("the price for the year %i is %f" %(year,price))
print('Jean bought {} item(s) at a price of {} each for a total of {}'.format(num_items, price, num_items*price))

the price for the year 2018 is 3.24
the price is 5
the price is 3.240000
the price for the year 2018 is 3.240000
Jean bought 5 item(s) at a price of 3.24 each for a total of 16.200000000000003


### Functions

In [25]:
# add_numbers is a function that takes two numbers and adds them together.
def add_numbers(x1, x2):
    return x1 + x2

t=add_numbers(1, 2)
print(t)

def printing():
    print('test')
printing()

3
test


In [26]:
# A function can be  assigned to a variable 
def add_numbers(x1, x2):
    z= x1 + x2
    return z

a = add_numbers
a(1,2)

3

### Conditional statements

In [27]:
x1 = 2
x2 = 7
if x1 > 5:
    print ('x1 is greater than 5')
else:
    print ('x1 is smaller than 5')

x1 is smaller than 5


In [28]:
if x1> 5 and x2 > 5:
    print ('x1 and x2 are greater than 5')
elif x1 > 5 or x2 >5:
    print ('x1 or x2 is greater than 5')
else:
    print ('x1 and x2 are smaller than 5')

x1 or x2 is greater than 5


<br>
# The Python Programming Language: Advanced Types

## Lists

In [30]:
x = [1, 'a', 2, 'hello', 3, True]  # Use brackets
print(x)
print (type(x))

[1, 'a', 2, 'hello', 3, True]
<class 'list'>


<br>
Lists are indexed in the same way as strings

In [31]:
print (x[0])
print (x[1:3])
print (x[-2:])
print (x[-1])
print (x[::-1])

1
['a', 2]
[3, True]
True
[True, 3, 'hello', 2, 'a', 1]


<br>
Lists are a mutable data structure ==> changed after création

In [37]:
x.append(3.3)  # Use append to append an object to a list
print (x)
x[0] = -1    # Change the value of the first element from 1 to -1
print (x)
print(type(x[0]))

[-1, 'a', 2, 'hello', 3, True, 3.3, 3.3, 3.3]
[-1, 'a', 2, 'hello', 3, True, 3.3, 3.3, 3.3]
<class 'int'>


<br>
This is an example of how to loop through each item in the list.

In [33]:
for blabla in x:
    print(blabla)

-1
a
2
hello
3
True
3.3


In [34]:
print ([1,2] + [3,4])   # Use + to concatenate lists
print ([1]*3)  # Use * to repeat lists
print (1 in [1, 2, 3])  # Use the in operator to check if something is inside a list
print ('Mimo' in ['Kimo', 'Mimo', 'dodo'])  # Use the in operator to check if something is inside a list

[1, 2, 3, 4]
[1, 1, 1]
True
True


## Tuples

In [35]:
t = (1, 'a', 2, 'hello', 3, True)  # Use parenthesis
print (t, type(t))

(1, 'a', 2, 'hello', 3, True) <class 'tuple'>


<br>
Tuples are indexed in the same way as strings, lists

In [38]:
print (t[0])
print (t[1:3])
print (t[-2:])

1
('a', 2)
(3, True)


<br>
Tuples are an immutable data structure ==> cannot be altered

In [39]:
t[0] = -1

TypeError: 'tuple' object does not support item assignment

## Dictionaries 
Dictionaries associate keys with values.

In [42]:
d = {'Toufic Zaraket': 'toufic.zaraket@edu.ece.fr', 'Hakim Idjis': 'hakim.idjis@edu.ece.fr'}  # Use curly brackets
print(d)
print (d, type(d))

{'Toufic Zaraket': 'toufic.zaraket@edu.ece.fr', 'Hakim Idjis': 'hakim.idjis@edu.ece.fr'}
{'Toufic Zaraket': 'toufic.zaraket@edu.ece.fr', 'Hakim Idjis': 'hakim.idjis@edu.ece.fr'} <class 'dict'>


<br>
Dictionaries are not indexed in the same way as strings, lists or tuples, we use the keys instead

In [43]:
d['Toufic Zaraket'] # Retrieve a value by using the indexing operator

'toufic.zaraket@edu.ece.fr'

<br>
Retrieve the keys

In [46]:
#for toto in d:   
#    print(toto)

# You can also use: for email in d.keys()

for blabla in d.keys():
    print(blabla)
    

Toufic Zaraket
Hakim Idjis


<br>
Retrieve the values:

In [47]:
#for blabla in d:
#    print(d[blabla])
    
# An other way of doing the same thing
#print ('****** 2nd method ***********')

for blabla in d.keys():
   print(blabla)
print( '*'*50)
for toto in d.values():
    print(toto)

Toufic Zaraket
Hakim Idjis
**************************************************
toufic.zaraket@edu.ece.fr
hakim.idjis@edu.ece.fr


<br>
Iterate over all of the items in the list:

In [48]:
for key, value in d.items():
    print(key,':',value)
    #print(email)

#print ('*'*50)
#for toto in d:
#    print(toto,',',d[toto])


Toufic Zaraket : toufic.zaraket@edu.ece.fr
Hakim Idjis : hakim.idjis@edu.ece.fr


<br>
# The Python Programming Language: Dates and Times

In [49]:
import datetime as dt
import time as tm

<br>
`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [57]:
print(tm.time())
print(dt.datetime.now())

1641305133.777857
2022-01-04 15:05:33.778517


<br>
Convert the timestamp to datetime.

In [58]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2022, 1, 4, 15, 5, 40, 998482)

<br>
Handy datetime attributes:

In [59]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2022, 1, 4, 15, 5, 40)

In [60]:
print(dtnow.month)

dtnow.strftime('%b')

1


'Jan'

<br>
`timedelta` is a duration expressing the difference between two dates.

In [61]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
print(type(delta))
print(delta)

<class 'datetime.timedelta'>
100 days, 0:00:00


<br>
`date.today` returns the current local date.

In [63]:
today = dt.date.today()
print(today)
print(type(today))

2022-01-04
<class 'datetime.date'>


In [64]:
today - delta # the date 100 days ago

datetime.date(2021, 9, 26)

In [65]:
today > today-delta # compare dates

True

<br>
# The Python Programming Language: Lambda and List Comprehensions

<br>
Here's an example of lambda that takes in three parameters and adds the first two.

In [66]:
my_function = lambda a, b, c : a + b

In [67]:
my_function(1, 2, 3)

3

<br>
Let's iterate from 0 to 999 and return the even numbers.

In [68]:
#my_list= list()
my_list = []
for number in range(0, 20):
    if number % 3 == 0:
        my_list.append(number)
print('my_list contins the following items:',my_list)

my_list contins the following items: [0, 3, 6, 9, 12, 15, 18]


<br>
Now the same thing but with list comprehension.

In [74]:
my_list = [number for number in range(0,20) if number % 3 == 0]
my_list

[0, 3, 6, 9, 12, 15, 18]

<br>
# The Python Programming Language: Numerical Python (NumPy)

In [76]:
import numpy as np

<br>
## Creating Arrays

Create a list and convert it to a numpy array

In [82]:
mylist = [1, 2, 3]
x = np.array(mylist)
y = np.array([1,2,3])
x
y

array([1, 2, 3])

<br>
Or just pass in a list directly

In [83]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

<br>
Pass in a list of lists to create a multidimensional array.

In [84]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [85]:
m = m.reshape(3,2)

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [86]:
m.shape

(3, 2)

<br>
`arange` returns evenly spaced values within a given interval.

In [87]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>
`reshape` returns an array with the same data with a new shape.

In [88]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

<br>
`linspace` returns evenly spaced numbers over a specified interval.

In [89]:
o = np.linspace(0, 10, 4) # return 9 evenly spaced values from 0 to 4
o

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

<br>
`ones` returns a new array of given shape and type, filled with ones.

In [90]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<br>
`zeros` returns a new array of given shape and type, filled with zeros.

In [91]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

<br>
`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [92]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<br>
Create an array using repeating list

In [93]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

<br>
Repeat elements of an array using `repeat`.

In [94]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [95]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [96]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


<br>
Use `.dtype` to see the data type of the elements in the array.

In [97]:
x.dtype

dtype('int64')

<br>
Use `.astype` to cast to a specific type.

In [98]:
x = x.astype('f')
x.dtype

dtype('float32')

In [99]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1. 4. 9.]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [100]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32.0

<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [101]:
a = np.array([-4, -2, 1, 3, 5])

In [102]:
a.sum()

3

In [103]:
a.max()

5

In [104]:
a.min()

-4

In [105]:
a.mean()

0.6

In [106]:
a.std()

3.2619012860600183

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [107]:
a.argmax()

4

In [108]:
a.argmin()

0

<br>
## Indexing / Slicing

In [109]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [110]:
s[0], s[4], s[-1]

(0, 16, 144)

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [111]:
s[-5::-2]

array([64, 36, 16,  4,  0])

<br>
Let's look at a multidimensional array.

In [112]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Use bracket notation to slice: `array[row, column]`

In [113]:
r[2, 2]

14

<br>
And use : to select a range of rows or columns

In [114]:
r[3, 3:6]

array([21, 22, 23])

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [115]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [116]:
r[r > 30]

array([31, 32, 33, 34, 35])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [117]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [118]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

<br>
Set this slice's values to zero ([:] selects the entire array)

In [119]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<br>
`r` has also been changed!

In [120]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [121]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
Now when r_copy is modified, r will not be changed.

In [122]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [123]:
test = np.random.randint(0, 10, (4,3))  # Generate a random integer in range 0-9 into a 4*3 array
test

array([[9, 5, 0],
       [7, 7, 5],
       [3, 9, 0],
       [4, 3, 1]])

In [124]:
test = np.random.randint(0, 10, 2)  # Generate a random integer in range 0-9 into a 4*3 array
print(test)

[1 4]


<br>
Iterate by row:

In [126]:
for row in test:
    print(row)

1
4


<br>
Iterate by index:

In [127]:
print (test.shape)
for i in range(test.shape[0]):
    print(test[i])

(2,)
1
4


<br>
Iterate by row and index:

In [128]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is 1
row 1 is 4
